ci.yml: Upgraded poetry to 1.6.1
Getting some weird SolverProblemError failures related to sshtunnel ^0.4.0 ,
Possibly related to https://github.com/python-poetry/poetry/issues/1614 :

```
Creating virtualenv couchbase-cluster-admin-Zcl4Ty5o-py3.8 in /home/runner/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because couchbase-cluster-admin depends on sshtunnel (^0.4.0) which doesn't match any versions, version solving failed.

  at /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
Error: Process completed with exit code 1.
```